### ISSUE TITLE
Bug with King not being able to move to a valid square

### ISSUE THREAD

**Issue by DMFriends** [timwoelfle/PlainChess#23]
![image](https://user-images.githubusercontent.com/86751519/164133391-dc9b477c-7509-4c30-9492-1b4c335758e4.png)

In this position, Black wants to move to Kf8, but on the website, it's not allowed, however it is a valid move in the game.

**Comment by timwoelfle** [comment]
Thanks for taking the time to report these bugs! I hope they're fixed now, let me know in case you find something else!
