### ISSUE TITLE
Exception when starting a new game

### ISSUE THREAD

**Issue by funtimesspray** [timwoelfle/PlainChess#24]
@timwoelfle 

It appears that one of the three recent commits have broken the game. Getting the following exception when starting a new offline game:

```
game.min.js:37 Uncaught TypeError: h(...).updateReachables is not a function
    at HTMLDivElement.<anonymous> (game.min.js:37:183)
    at Function.each (jquery-3.6.0.min.js:2:3003)
    at S.fn.init.each (jquery-3.6.0.min.js:2:1481)
    at game.min.js:37:159
    at new Game (game.min.js:39:206)
    at Object.menuOption (game.min.js:52:202)
    at HTMLAnchorElement.<anonymous> (game.min.js:49:31)
    at HTMLAnchorElement.dispatch (jquery-3.6.0.min.js:2:43064)
    at HTMLAnchorElement.v.handle (jquery-3.6.0.min.js:2:41048)
(anonymous) @ game.min.js:37
each @ jquery-3.6.0.min.js:2
each @ jquery-3.6.0.min.js:2
(anonymous) @ game.min.js:37
Game @ game.min.js:39
menuOption @ game.min.js:52
(anonymous) @ game.min.js:49
dispatch @ jquery-3.6.0.min.js:2
v.handle @ jquery-3.6.0.min.js:2
```

Each click of "Play Offline" creates a new set of pieces:

![plainchess](https://user-images.githubusercontent.com/49293425/165216812-942bf30f-0262-42dd-bd26-191ef7f681e9.jpg)

OS: `macOS 12.3`
Browser: `Chrome Version 100.0.4896.127 (Official Build) (x86_64)`

**Comment by timwoelfle** [comment]
Thanks for taking the time to report! Can you try again after force-reloading the page (F5)? Sometimes old scripts are cached.

**Comment by funtimesspray** [comment]
> Thanks for taking the time to report! Can you try again after force-reloading the page (F5)? Sometimes old scripts are cached.

I should have added this to the original report. This was tested with a fresh session and in incognito mode to make sure nothing was cached.

**Comment by funtimesspray** [comment]
@timwoelfle 

I re-tested this on a machine with a fresh install of macOS and I didn't see the issue occur. It's still happening on my other machine but I'll figure that out on my own. Closing this issue.

**Comment by timwoelfle** [comment]
That's weird, let me know if you figured it out. Thanks and best!
