### ISSUE TITLE
Misinterpreted Checkmate 

### ISSUE THREAD

**Issue by JSybrandt** [timwoelfle/PlainChess#5]
![bug](https://cloud.githubusercontent.com/assets/2685772/11139938/33c10dbc-89a3-11e5-8365-161dd046a486.PNG)

King is allowed to take Rook at B8

**Comment by Pawtiko** [comment]
No, he can't, because of Black's bishop in the bottom right. If White took the rook, he would still be in check from the bishop.

Checkmate.
