### ISSUE TITLE
Issue screenshot

### ISSUE THREAD

**Issue by jseymour1586** [timwoelfle/PlainChess#6]
![image](https://cloud.githubusercontent.com/assets/23740134/20625949/2b1d3c72-b30e-11e6-949a-18ea9bf5399e.png)

**Comment by jseymour1586** [comment]
i had move dthe king (originally in check) However it moved to a diffrent position (not my choice) t then happened to the queen and well there is a screenshot

**Comment by timwoelfle** [comment]
Hi, thanks for your bug report! Unfortunately, I’m not able to reproduce this bug. Is the game still on when you open PlainChess (is it still autosaved)? If so you could provide me with important additional information! Go to plainchess.timwoelfle.de, open the Chrome-console (Press Ctrl+Shift+J (Windows / Linux) or Cmd+Opt+J (Mac)) and enter "localStorage.gameState" as well as "localStorage.moves" and send me the corresponding outputs. With this information I might be able to fix the bug. Thanks!

**Comment by jseymour1586** [comment]
Sadly I was playing on a collage computer hence I cannot access it at the moment and I can never access the history as it deletes after logout
My apologies.

Sent from my iPhone

On 25 Nov 2016, at 15:16, Tim W?lfle <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, thanks for your bug report! Unfortunately, I'm not able to reproduce this bug. Is the game still on when you open PlainChess (is it still autosaved)? If so you could provide me with important additional information! Go to plainchess.timwoelfle.de<http://plainchess.timwoelfle.de>, open the Chrome-console (Press Ctrl+Shift+J (Windows / Linux) or Cmd+Opt+J (Mac)) and enter "localStorage.gameState" as well as "localStorage.moves" and send me the corresponding outputs. With this information I might be able to fix the bug. Thanks!

-

**Comment by timwoelfle** [comment]
Alright, thanks anyway. If it happens again you know what to do ;) Just for clarification: you were playing white and wanted to move the king from f2 to g1 as stated. Instead it went to g3. Did it move there smoothly? What exactly happened to the black queen? Was it moved by your opponent and if so, do you remember where to? Did it move smoothly to the rook? Was the rook at the same position before? Did anything happen to the rook after the queen moved there?
